spring.application.name=auth-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/pharmtrack

server.port=8082

keycloak.server-url=http://localhost:9090
keycloak.realm=pharmtrack
keycloak.client-id=pharmtrack-backend-client
keycloak.client-secret=${CLIENT_SECRET}
