server.port=8085

spring.application.name=notification-service

spring.mail.host=smtp.gmail.com
spring.mail.port=581
spring.mail.username=${APP_MAIL}
spring.mail.password=${EMAIL_APP_PASSWORD}

spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
