server.port=8084

spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5436/order-postgres-db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/pharmtrack

spring.kafka.bootstrap-servers=http://localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all

order-topic=order-topic

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}