spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5436/order-postgres-db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}

spring.jpa.hibernate.ddl-auto=update